# Katalog zdarzeń dźwiękowych gry: dla każdego — zapytanie do opisów próbek Freesound (CC0), docelowa długość i liczba wariantów.
# q: słowa/frazy w tytule albo tagach (każde trafienie podnosi wynik), need: przynajmniej jedno musi wystąpić, no: wyklucza,
# dur: maksymalna długość wyciętego fragmentu (s), n: ile wariantów, cut: 'onsets' = warianty z kolejnych uderzeń jednego nagrania
# (kroki, kopyta), 'whole' = cała próbka (przycięta), lp: filtr dolnoprzepustowy (Hz) dla stłumionej wersji, gain: korekta dB.
CAT = {
  'click':     dict(q=['wood click', 'wooden click', 'button click', 'click wood', 'ui click', 'tick'], need=['click', 'tick'], no=['mouse', 'pen', 'camera', 'keyboard', 'tongue'], dur=0.18, n=2),
  'page':      dict(q=['page turn', 'paper', 'parchment', 'page flip', 'book page'], need=['page', 'paper', 'parchment'], no=['tear', 'crumple', 'shred'], dur=0.55, n=2, cut='onsets'),
  'book':      dict(q=['book open', 'book close', 'old book', 'leather book', 'book'], need=['book'], no=['facebook', 'notebook', 'audiobook'], dur=0.8, n=1),
  'hoof':      dict(q=['horse hooves', 'horse walk', 'horse trot', 'hoofbeat', 'horse gallop', 'hooves'], need=['horse', 'hoof', 'hooves'], no=['neigh', 'whinny', 'carriage', 'toy'], dur=0.32, n=4, cut='onsets', group=2),
  'hoofsnow':  dict(src='hoof', lp=1400, gain=-3, dur=0.32, n=3),
  'gallop':    dict(src='hoof', dur=0.22, n=4, gain=-2),
  'oar':       dict(q=['oar', 'rowing', 'paddle', 'row boat', 'oars'], need=['oar', 'rowing', 'paddle', 'row'], no=['kayak race'], dur=0.7, n=2, cut='onsets'),
  'coins':     dict(q=['coins', 'coin', 'gold coins', 'money', 'coin drop'], need=['coin', 'coins'], no=['arcade', '8bit', '8-bit', 'game coin', 'mario', 'retro', 'synth'], dur=0.9, n=2),
  'pickup':    dict(q=['sack', 'leather bag', 'bag drop', 'pick up', 'wood drop', 'cloth'], need=['sack', 'bag', 'pick', 'drop'], no=['plastic', 'paper bag', 'chips'], dur=0.5, n=2, cut='onsets'),
  'chest':     dict(q=['chest open', 'wooden chest', 'box open', 'creak', 'lid', 'trunk open'], need=['chest', 'box', 'lid', 'trunk'], no=['cough', 'breath', 'drawer'], dur=1.1, n=1),
  'artifact':  dict(q=['magic chime', 'magical sparkle', 'shimmer', 'chime', 'sparkle'], need=['chime', 'sparkle', 'shimmer', 'magic'], no=['doorbell', 'phone', 'notification', 'alarm'], dur=1.4, n=1),
  'shrine':    dict(q=['bell', 'singing bowl', 'chime', 'church bell', 'temple bell'], need=['bell', 'bowl', 'chime'], no=['bike', 'bicycle', 'door', 'school', 'phone', 'alarm'], dur=1.6, n=1),
  'flag':      dict(q=['flag flapping', 'banner', 'flag wind', 'cloth flap', 'flag'], need=['flag', 'banner', 'flap'], no=[], dur=0.9, n=1),
  'build':     dict(q=['hammer', 'hammering', 'hammer wood', 'nail', 'construction', 'carpentry'], need=['hammer', 'hammering', 'carpentry'], no=['drill', 'power', 'electric', 'jackhammer'], dur=1.0, n=2, cut='onsets'),
  'recruit':   dict(q=['chainmail', 'armor', 'armour', 'sword unsheath', 'sword draw', 'metal rattle'], need=['chainmail', 'armor', 'armour', 'sheath', 'unsheath'], no=[], dur=0.8, n=2),
  'battlestart': dict(q=['war horn', 'battle horn', 'horn blow', 'viking horn', 'horn'], need=['horn'], no=['car', 'truck', 'train', 'air horn', 'bike', 'ship'], dur=3.0, n=1),
  'victory':   dict(q=['fanfare', 'trumpet fanfare', 'brass fanfare', 'victory fanfare', 'royal fanfare'], need=['fanfare'], no=['8bit', '8-bit', 'chiptune', 'synth', 'retro', 'game over'], dur=4.5, n=1),
  'defeat':    dict(q=['gong', 'funeral', 'drum', 'timpani', 'low gong', 'death drum'], need=['gong', 'timpani'], no=['8bit', 'synth'], dur=3.5, n=1),
  'march':     dict(q=['footsteps armor', 'marching', 'footsteps gravel', 'boots gravel', 'footstep dirt', 'footsteps'], need=['footstep', 'footsteps', 'marching', 'march'], no=['high heels', 'heels', 'stairs', 'wood floor', 'tile', 'snow'], dur=0.22, n=4, cut='onsets'),
  'wings':     dict(q=['wings flap', 'flapping wings', 'wing flap', 'bird wings', 'wings'], need=['wing', 'wings', 'flap'], no=['insect', 'bee', 'fly buzz'], dur=0.8, n=2),
  'stomp':     dict(q=['heavy footstep', 'giant footstep', 'stomp', 'monster footstep', 'heavy steps'], need=['stomp', 'heavy', 'giant'], no=[], dur=0.5, n=3, cut='onsets'),
  'paws':      dict(q=['dog running', 'paws', 'animal footsteps', 'dog paws', 'running dog'], need=['paw', 'paws', 'dog', 'animal'], no=['bark', 'bowl'], dur=0.25, n=3, cut='onsets'),
  'roar':      dict(q=['dragon roar', 'monster roar', 'creature roar', 'beast roar', 'roar'], need=['roar'], no=['crowd', 'engine', 'car', 'motorcycle', 'lion cub'], dur=1.5, n=2),
  'growl':     dict(q=['growl', 'wolf growl', 'snarl', 'monster growl', 'creature growl'], need=['growl', 'snarl'], no=['stomach', 'tummy', 'cat'], dur=0.9, n=2),
  'swing':     dict(q=['sword swing', 'sword whoosh', 'swoosh', 'whoosh', 'swish'], need=['swing', 'whoosh', 'swoosh', 'swish'], no=['golf', 'bat', 'door', 'car', 'rope'], dur=0.45, n=3, cut='onsets'),
  'clash':     dict(q=['sword clash', 'sword hit', 'swords clash', 'blade', 'metal clang', 'sword impact'], need=['sword', 'blade', 'clang'], no=['sharpen', 'unsheath', 'sheath'], dur=0.7, n=3),
  'hit':       dict(q=['punch', 'body hit', 'impact', 'hit', 'thump', 'body blow'], need=['punch', 'hit', 'impact', 'thump'], no=['car crash', 'glass', 'metal', 'door', 'game', '8bit'], dur=0.4, n=3, cut='onsets'),
  'arrowhit':  dict(q=['arrow impact', 'arrow hit', 'arrow wood', 'arrow target', 'arrow thud'], need=['arrow'], no=['bow release'], dur=0.45, n=2),
  'death':     dict(q=['body fall', 'body drop', 'fall down', 'death groan', 'groan', 'thud'], need=['fall', 'drop', 'groan', 'thud'], no=['water', 'glass', 'rain', 'leaves'], dur=0.8, n=2, cut='onsets'),
  'bow':       dict(q=['bow release', 'arrow shot', 'bow shot', 'arrow whoosh', 'archery'], need=['bow', 'arrow', 'archery'], no=['violin', 'cello', 'impact'], dur=0.6, n=2),
  'zap':       dict(q=['magic zap', 'magic missile', 'magic shot', 'spell cast', 'zap'], need=['magic', 'zap', 'spell'], no=['8bit', '8-bit', 'retro', 'laser gun'], dur=0.6, n=2),
  'zaphit':    dict(q=['magic impact', 'magic hit', 'energy impact', 'spell impact'], need=['magic', 'energy', 'spell'], no=['8bit', 'retro'], dur=0.6, n=1),
  'cast':      dict(q=['spell cast', 'magic spell', 'magic whoosh', 'casting', 'magic'], need=['spell', 'magic', 'cast'], no=['8bit', '8-bit', 'retro', 'trick'], dur=0.9, n=2),
  'thunder':   dict(q=['thunder', 'lightning strike', 'thunder crack', 'thunderclap', 'lightning'], need=['thunder', 'lightning'], no=['rain loop', 'distant'], dur=1.8, n=2),
  'fireball':  dict(q=['fireball', 'fire whoosh', 'flame whoosh', 'fire woosh', 'torch whoosh'], need=['fire', 'flame', 'fireball'], no=['alarm', 'crackling', 'campfire', 'fireplace', 'gun'], dur=0.9, n=1),
  'explode':   dict(q=['explosion', 'explode', 'blast', 'boom', 'fire explosion'], need=['explosion', 'explode', 'blast', 'boom'], no=['firework', 'gun', 'cannon', 'bubble'], dur=1.8, n=2),
  'firebreath': dict(q=['flamethrower', 'fire breath', 'fire burst', 'flame burst', 'dragon fire'], need=['flamethrower', 'breath', 'burst', 'flame'], no=['gas stove'], dur=1.2, n=1),
  'ice':       dict(q=['ice crack', 'ice shatter', 'ice break', 'freeze', 'ice'], need=['ice', 'freeze', 'frozen'], no=['cream', 'cube drink', 'glass of'], dur=1.0, n=1),
  'heal':      dict(q=['healing', 'heal', 'harp', 'magic chime', 'angelic'], need=['heal', 'harp', 'chime', 'angelic'], no=['phone', 'notification', 'doorbell'], dur=1.4, n=1),
  'buff':      dict(q=['power up', 'magic shimmer', 'enchant', 'magic spell', 'shimmer'], need=['power', 'shimmer', 'enchant', 'magic'], no=['8bit', '8-bit', 'retro', 'arcade'], dur=1.1, n=1),
  'curse':     dict(q=['dark magic', 'evil spell', 'curse', 'ghost whoosh', 'evil whoosh'], need=['dark', 'evil', 'curse', 'ghost'], no=['laugh', 'voice'], dur=1.2, n=1),
  'catapult':  dict(q=['catapult', 'trebuchet', 'catapult launch', 'wood creak'], need=['catapult', 'trebuchet'], no=[], dur=1.0, n=1),
  'crash':     dict(q=['stone crash', 'wall collapse', 'rock impact', 'rubble', 'debris'], need=['stone', 'rock', 'rubble', 'debris', 'collapse'], no=['music', 'glass'], dur=1.5, n=2),
  'thud':      dict(q=['rock thud', 'boulder', 'stone thud', 'heavy thud', 'stone impact'], need=['rock', 'boulder', 'stone', 'thud'], no=['music'], dur=0.8, n=1),
}
